#!/usr/bin/env python3
"""Regenerate the TypeScript engine's byte-identical goldens from the Python reference engine.

Run with:

    cd /Users/willsct/agentce && env -u VIRTUAL_ENV uv run --project engines/python --frozen \\
        python engines/typescript/testdata/generate_goldens.py

Why this script exists: ``engines/typescript/src/{assess,catalog,report}.test.ts`` each assert that
the TypeScript engine's output is byte-identical (after RFC 8785 canonicalisation) to the Python
reference engine's output over the real ``spec/catalogs/base/eu-ai-act`` catalog. The three JSON
goldens this script writes under ``engines/typescript/testdata/`` are, by design, captures of the
*Python reference engine's* output — never the TypeScript engine's own output, because comparing the
TypeScript engine to itself would make the parity tests vacuous. Whenever the base catalog gains,
removes, or changes a control, shape, or test fixture, these goldens go stale (they no longer reflect
the same inputs the live catalog would produce) and must be regenerated by re-running this script
against the then-current catalog. It imports the ``agentce`` package directly (never the TypeScript
engine) and calls the same reference functions the three TS tests describe in their own doc comments.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(REPO / "engines" / "python"))

from agentce.assertions import Assertion, aggregate  # noqa: E402
from agentce.assess import assess_subjects  # noqa: E402
from agentce.catalog import Catalog, load_catalog  # noqa: E402
from agentce.domain import DomainBinding  # noqa: E402
from agentce.graph import build_graph  # noqa: E402
from agentce.profile import Profile  # noqa: E402
from agentce.report import (  # noqa: E402
    render_evidence_pack,
    render_oscal,
    render_report_html,
    render_report_md,
    render_sarif,
)
from agentce.structural import evaluate_control  # noqa: E402

BASE = REPO / "spec" / "catalogs" / "base" / "eu-ai-act"
TESTDATA = REPO / "engines" / "typescript" / "testdata"
SUBJECT = "spiffe://corp/agents/a"
CASES = ("passed", "failed", "inapplicable")


def events_of(control_id: str, case: str) -> list[dict[str, object]]:
    """Parse a fixture's JSONL lines the same way the TS tests' own readers do."""
    path = BASE / "test" / control_id / f"{case}.jsonl"
    return [
        json.loads(line)
        for line in path.read_text(encoding="utf-8").split("\n")
        if line.strip()
    ]


def write_golden(name: str, data: object) -> None:
    """Write ``data`` in the same style as the existing goldens: 2-space indent, sorted keys, a
    trailing newline, and no other file touched."""
    path = TESTDATA / name
    path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"wrote {path}")


def build_assess_golden(catalog: Catalog, domain: DomainBinding) -> dict[str, object]:
    """Mirrors engines/typescript/src/assess.test.ts."""
    profile = Profile.from_dict(
        {
            "subjects": [{"id": SUBJECT, "role": "both"}],
            "catalogs": ["base/eu-ai-act"],
        }
    )
    scenarios: dict[str, list[dict[str, object]]] = {
        "ovs-passed": events_of("OVS-03", "passed"),
        "ovs-failed": events_of("OVS-03", "failed"),
        "rec-passed": events_of("REC-04", "passed"),
        "empty": [],
    }
    result: dict[str, object] = {}
    for name, events in scenarios.items():
        assertions = assess_subjects(events, profile, [catalog], domain)
        result[name] = [a.to_json() for a in assertions]
    return result


def build_catalog_golden(catalog: Catalog, domain: DomainBinding) -> dict[str, object]:
    """Mirrors engines/typescript/src/catalog.test.ts (lines 32-55): skip a control with no usable
    shape, skip a case with no fixture, but still record every control that has a shape (even with an
    empty per-case map) exactly as the TS loop does."""
    result: dict[str, object] = {}
    for control in catalog.controls:
        shape = catalog.shape_for(control)
        if shape is None:
            continue
        per_case: dict[str, object] = {}
        for case in CASES:
            fixture = BASE / "test" / control.id / f"{case}.jsonl"
            if not fixture.is_file():
                continue
            events = events_of(control.id, case)
            store = build_graph(events, domain=domain)
            outcome = evaluate_control(
                store,
                shape,
                catalog.shapes,
                control_id=control.id,
                tolerance=control.tolerance,
            )
            per_case[case] = outcome.to_json()
        result[control.id] = per_case
    return result


#: Synthetic (control, subject, outcome) sets that exercise every verdict state, the gap cap, and a
#: control assessed for two subjects. Each engine rebuilds these assertions and renders them.
VERDICT_CASES: list[list[list[str]]] = [
    [
        *(
            [f"DAT-{n:02d}", "spiffe://corp/agents/a", "insufficient_evidence"]
            for n in range(8, 0, -1)
        ),
        ["DOC-01", "spiffe://corp/agents/a", "conformant"],
        ["DOC-05", "spiffe://corp/agents/a", "not_assessed"],
        ["OVS-09", "spiffe://corp/agents/a", "not_assessed"],
    ],
    [
        ["DOC-01", "spiffe://corp/agents/a", "conformant"],
        ["DOC-02", "spiffe://corp/agents/a", "conformant"],
        ["INC-02", "spiffe://corp/agents/a", "not_applicable"],
    ],
    [
        ["OVS-02", "spiffe://corp/agents/a", "non-conformant"],
        ["OVS-02", "spiffe://corp/agents/b", "non-conformant"],
        ["REC-01", "spiffe://corp/agents/a", "partial"],
        ["REC-02", "spiffe://corp/agents/b", "insufficient_evidence"],
    ],
]


def build_verdict_cases() -> list[dict[str, object]]:
    cases: list[dict[str, object]] = []
    for rows in VERDICT_CASES:
        assertions = [
            Assertion(
                control=control,
                control_version="2026.09",
                subject=subject,
                outcome=outcome,
                rung=2,
                mode="automated",
                window=("2026-01-01T00:00:00Z", "2026-04-01T00:00:00Z"),
                population=(1, 1 if outcome == "non-conformant" else 0),
            )
            for control, subject, outcome in rows
        ]
        counts = aggregate(assertions)
        cases.append(
            {
                "assertions": rows,
                "md": render_report_md(assertions, counts),
                "html": render_report_html(assertions, counts),
            }
        )
    return cases


def build_report_golden(catalog: Catalog, domain: DomainBinding) -> dict[str, object]:
    """Mirrors engines/typescript/src/report.test.ts (lines 35-63); the SARIF driver name is
    normalised to ``agentce-ts`` since it is the only field that names the implementation
    (Python's render_sarif otherwise stamps its own ENGINE_NAME, "agentce-py")."""
    profile = Profile.from_dict({"subjects": [{"id": SUBJECT, "role": "both"}]})
    events = events_of("OVS-03", "failed")
    assertions: list[Assertion] = assess_subjects(events, profile, [catalog], domain)
    counts = aggregate(assertions)

    sarif = render_sarif(assertions)
    sarif["runs"][0]["tool"]["driver"]["name"] = "agentce-ts"

    return {
        "md": render_report_md(assertions, counts),
        "html": render_report_html(assertions, counts),
        "oscal": render_oscal(assertions),
        "sarif": sarif,
        "pack": render_evidence_pack(SUBJECT, assertions),
        "assertions": [a.to_json() for a in assertions],
        "verdict_cases": build_verdict_cases(),
    }


def main() -> None:
    catalog = load_catalog(BASE)
    domain = DomainBinding.load(BASE / "test" / "domain.yaml")

    write_golden("assess-golden.json", build_assess_golden(catalog, domain))
    write_golden("catalog-golden.json", build_catalog_golden(catalog, domain))
    write_golden("report-golden.json", build_report_golden(catalog, domain))


if __name__ == "__main__":
    main()
