// Serve every canonical agent-conformance.org IRI from the built site.
//
// Runs after `astro build`. For each entry in iri-manifest.json it copies the spec/ source file into
// website/dist/ at the entry's canonical path, byte-for-byte, and records the entry's content type in a
// Cloudflare-style `_headers` file. The specification sources stay the single source of truth; nothing
// is vendored into the repository, and check-iris.mjs verifies the copies have not drifted.
import { readFileSync, copyFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const websiteDir = resolve(scriptDir, '..');
const repoRoot = resolve(scriptDir, '..', '..');
const dist = join(websiteDir, 'dist');

const manifest = JSON.parse(readFileSync(join(websiteDir, 'iri-manifest.json'), 'utf8'));

let headers = '# Canonical IRI content types — generated by scripts/build-iris.mjs, do not edit.\n';
for (const { path, source, content_type } of manifest) {
  const dest = join(dist, path.replace(/^\//, ''));
  mkdirSync(dirname(dest), { recursive: true });
  copyFileSync(join(repoRoot, source), dest);
  headers += `${path}\n  Content-Type: ${content_type}\n`;
}
writeFileSync(join(dist, '_headers'), headers);

console.log(`build-iris: served ${manifest.length} canonical IRIs into dist/ with a _headers map.`);
