#!/usr/bin/env node
// quickstart-hero — keep the landing-page terminal equal to a real `agentce quickstart` run.
//
// The hero terminal in src/pages/index.astro is generated, never typed: this script runs the real
// quickstart over the bundled corpus/quickstart project, builds the terminal and its caption from that
// run's own stdout and report.md, and either rewrites the marked region of the page (--write) or fails
// when the committed page no longer equals a fresh run (--check, the default). A committed transcript
// that stops matching the engine is therefore a build failure, not a silent drift.
//
//   node scripts/quickstart-hero.mjs [PAGE]          fail (exit 1) unless the page equals a fresh run
//   node scripts/quickstart-hero.mjs --write [PAGE]  regenerate the marked region from a fresh run
//   node scripts/quickstart-hero.mjs --self-test prove the check fails on a stale or fabricated hero
//
// Exit codes: 0 ok · 1 the page differs from a fresh run · 2 the run itself could not be made.
// No network, no learned component; the run is the offline engine over a committed bundle.

import { spawnSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const SITE = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const ROOT = resolve(SITE, '..');
const PAGE = join(SITE, 'src', 'pages', 'index.astro');

const BEGIN = '{/* quickstart-run:begin — generated by scripts/quickstart-hero.mjs, do not edit by hand */}';
const END = '{/* quickstart-run:end */}';
const COMMAND = 'agentce quickstart --out ./out';

// Sentences the real CLI never emits. They stay banned so a hand-written all-pass transcript cannot return.
const FORBIDDEN = ['every control conformant', 'Assessment complete. Every verdict cites the evidence'];

// Outcome vocabulary in report order: [assertions.json value, report.md label, caption label].
const OUTCOMES = [
  ['conformant', 'conformant', 'conformant'],
  ['non-conformant', 'non-conformant', 'non-conformant'],
  ['partial', 'partial', 'partial'],
  ['not_applicable', 'not applicable', 'not applicable'],
  ['not_assessed', 'not assessed', 'not assessed'],
  ['insufficient_evidence', 'insufficient evidence', 'insufficient evidence'],
];
// The caption always names these three, even at zero, so the page never hides insufficient evidence.
const ALWAYS = new Set(['conformant', 'insufficient_evidence', 'not_assessed']);

const escapeHtml = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

/** Run the real quickstart in a scratch directory and return what the hero needs from it. */
export function runQuickstart() {
  const scratch = mkdtempSync(join(tmpdir(), 'quickstart-hero-'));
  try {
    const env = { ...process.env };
    delete env.VIRTUAL_ENV;
    const run = spawnSync(
      'uv',
      ['run', '--project', join(ROOT, 'engines', 'python'), '--frozen', 'agentce', 'quickstart', '--out', './out'],
      { cwd: scratch, env, encoding: 'utf8' },
    );
    if (run.error || run.status !== 0) {
      const why = run.error ? run.error.message : `exit ${run.status}\n${run.stderr}`;
      throw new Error(`quickstart did not run: ${why}`);
    }
    const stdout = run.stdout.replace(/\n+$/, '');
    const report = readFileSync(join(scratch, 'out', 'report.md'), 'utf8').split('\n');
    const assertions = JSON.parse(readFileSync(join(scratch, 'out', 'assertions.json'), 'utf8'));
    const counts = {};
    for (const a of assertions) counts[a.outcome] = (counts[a.outcome] ?? 0) + 1;
    return { stdout, report, counts, total: assertions.length };
  } finally {
    rmSync(scratch, { recursive: true, force: true });
  }
}

/** The lines of report.md up to and including the last Outcome-summary bullet, checked against the tally. */
export function summaryLines(run) {
  const start = run.report.indexOf('## Outcome summary');
  if (start < 0) throw new Error('report.md has no "## Outcome summary" section');
  let end = start + 1;
  const bullet = /^- (.+): (\d+)$/;
  while (end < run.report.length && (run.report[end] === '' || bullet.test(run.report[end]))) end += 1;
  while (run.report[end - 1] === '') end -= 1;
  const shown = {};
  for (const line of run.report.slice(start, end)) {
    const m = bullet.exec(line);
    if (m) shown[m[1]] = Number(m[2]);
  }
  for (const [key, label] of OUTCOMES) {
    if ((shown[label] ?? 0) !== (run.counts[key] ?? 0)) {
      throw new Error(`report.md says ${shown[label] ?? 0} ${label}, assertions.json has ${run.counts[key] ?? 0}`);
    }
  }
  return run.report.slice(0, end);
}

/** The generated block: the terminal transcript of the run, then a caption stating its tally. */
export function renderRegion(run) {
  const lines = summaryLines(run);
  const head = `head -n ${lines.length} out/report.md`;
  const transcript = [
    `<span class="c-prompt">$</span> <span class="c-cmd">${escapeHtml(COMMAND)}</span>`,
    escapeHtml(run.stdout),
    '',
    `<span class="c-prompt">$</span> <span class="c-cmd">${escapeHtml(head)}</span>`,
    ...lines.map(escapeHtml),
  ].join('\n');
  const tally = OUTCOMES.filter(([key]) => ALWAYS.has(key) || (run.counts[key] ?? 0) > 0)
    .map(([key, , label]) => `${run.counts[key] ?? 0} ${label}`)
    .join(', ');
  return [
    `      <pre><code>${transcript}</code></pre>`,
    '      <figcaption>',
    `        The real output of that command over the bundled <code>corpus/quickstart</code> project: ${tally}, of ${run.total} assertions.`,
    '        Where the evidence does not settle a control the engine reports insufficient evidence; it never guesses.',
    '      </figcaption>',
  ].join('\n');
}

/** Replace the marked region of a page with `region`; null if the markers are absent or misordered. */
export function spliceRegion(page, region) {
  const a = page.indexOf(BEGIN);
  const b = page.indexOf(END);
  if (a < 0 || b < 0 || b < a) return null;
  return `${page.slice(0, a + BEGIN.length)}\n${region}\n      ${page.slice(b)}`;
}

/** Empty when the page equals what a fresh run generates; otherwise the reasons it does not. */
export function checkPage(page, run) {
  const problems = [];
  for (const phrase of FORBIDDEN) {
    if (page.includes(phrase)) problems.push(`hero.forbidden_claim: the page states "${phrase}"`);
  }
  const fresh = spliceRegion(page, renderRegion(run));
  if (fresh === null) problems.push('hero.markers_missing: the quickstart-run markers are absent from the page');
  else if (fresh !== page) problems.push('hero.drift: the hero differs from a fresh quickstart run');
  return problems;
}

function selfTest() {
  const run = {
    stdout: 'quickstart complete: 5 assertions; report in ./out',
    report: [
      '# AgentCE conformance report',
      '',
      '## Outcome summary',
      '',
      '- conformant: 3',
      '- non-conformant: 0',
      '- partial: 0',
      '- not applicable: 0',
      '- not assessed: 1',
      '- insufficient evidence: 1',
      '',
      '## Assertions',
    ],
    counts: { conformant: 3, not_assessed: 1, insufficient_evidence: 1 },
    total: 5,
  };
  const shell = `<figure>\n      ${BEGIN}\n      ${END}\n    </figure>`;
  const good = spliceRegion(shell, renderRegion(run));
  const cases = [
    ['a page generated from the run passes', good, run, []],
    ['a changed tally is drift', good.replace('3 conformant', '4 conformant'), run, ['hero.drift']],
    ['a run that changed under the page is drift', good, { ...run, counts: { ...run.counts, conformant: 2, not_assessed: 2 }, report: run.report.map((l) => l.replace('conformant: 3', 'conformant: 2').replace('assessed: 1', 'assessed: 2')) }, ['hero.drift']],
    ['a hand-written all-pass claim is refused', good.replace('</figure>', '<p>every control conformant</p></figure>'), run, ['hero.forbidden_claim']],
    ['a page without markers is refused', '<figure></figure>', run, ['hero.markers_missing']],
  ];
  let failed = 0;
  for (const [name, page, r, expect] of cases) {
    const got = checkPage(page, r).map((p) => p.split(':')[0]);
    const ok = got.length === expect.length && expect.every((k) => got.includes(k));
    console.log(`${ok ? 'ok  ' : 'FAIL'} self-test: ${name}${ok ? '' : ` (expected [${expect}], got [${got}])`}`);
    if (!ok) failed += 1;
  }
  let inconsistent = false;
  try {
    summaryLines({ ...run, counts: { ...run.counts, conformant: 9 } });
  } catch {
    inconsistent = true;
  }
  console.log(`${inconsistent ? 'ok  ' : 'FAIL'} self-test: a report that disagrees with assertions.json is refused`);
  if (!inconsistent) failed += 1;
  return failed === 0 ? 0 : 1;
}

function main(argv) {
  if (argv.includes('--self-test')) return selfTest();
  let run;
  try {
    run = runQuickstart();
  } catch (err) {
    console.error(`hero.run_failed: ${err.message}`);
    return 2;
  }
  const pagePath = argv.find((a) => !a.startsWith('--')) ?? PAGE;
  const page = readFileSync(pagePath, 'utf8');
  if (argv.includes('--write')) {
    const next = spliceRegion(page, renderRegion(run));
    if (next === null) {
      console.error('hero.markers_missing: the quickstart-run markers are absent from the page');
      return 1;
    }
    writeFileSync(pagePath, next);
    console.log(`quickstart-hero: wrote the hero from a fresh run (${run.total} assertions)`);
    return 0;
  }
  const problems = checkPage(page, run);
  for (const p of problems) console.error(p);
  if (problems.length > 0) {
    console.error('fix: node scripts/quickstart-hero.mjs --write');
    return 1;
  }
  console.log(`quickstart-hero: the hero equals a fresh quickstart run (${run.total} assertions)`);
  return 0;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  process.exit(main(process.argv.slice(2)));
}
