#!/usr/bin/env node
// quickstart-hero — keep every page that states the quickstart result equal to a real `agentce quickstart` run.
//
// The landing-page terminal, the Getting Started outcome block, the docs quickstart page and the corpus
// quickstart README are generated, never typed: this script runs the real quickstart over the bundled
// corpus/quickstart project once, renders each surface's marked region from that run's own stdout,
// report.md and assertions.json, and either rewrites the regions (--write) or fails when a committed page no
// longer equals a fresh run (--check, the default). A committed transcript or tally that stops matching the
// engine, and a hand-written blanket "every control is conformant" claim, are therefore build failures, not
// silent drift.
//
//   node scripts/quickstart-hero.mjs [PAGE...]          fail (exit 1) unless the pages equal a fresh run
//   node scripts/quickstart-hero.mjs --write [PAGE...]  regenerate the marked regions from a fresh run
//   node scripts/quickstart-hero.mjs --self-test        prove the check fails on a stale or fabricated page
//
// With no PAGE the four surfaces are checked. A PAGE ending in .astro is a hero page (terminal transcript);
// any other PAGE is a Markdown page (tally and definitions).
//
// Exit codes: 0 ok · 1 a page differs from a fresh run · 2 the run itself could not be made.
// No network, no learned component; the run is the offline engine over a committed bundle.

import { spawnSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const SITE = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const ROOT = resolve(SITE, '..');
const SURFACES = [
  join(SITE, 'src', 'pages', 'index.astro'),
  join(SITE, 'src', 'content', 'docs', 'docs', 'getting-started.md'),
  join(ROOT, 'docs', 'quickstart.md'),
  join(ROOT, 'corpus', 'quickstart', 'README.md'),
];

const BEGIN = '{/* quickstart-run:begin — generated by scripts/quickstart-hero.mjs, do not edit by hand */}';
const END = '{/* quickstart-run:end */}';
const MD_BEGIN = '<!-- quickstart-run:begin — generated by website/scripts/quickstart-hero.mjs, do not edit by hand -->';
const MD_END = '<!-- quickstart-run:end -->';
const COMMAND = 'agentce quickstart --out ./out';

// Sentences the real CLI never emits. They stay banned so a hand-written all-pass transcript cannot return.
const FORBIDDEN = ['every control conformant', 'Assessment complete. Every verdict cites the evidence'];

// Outcome vocabulary in report order: [assertions.json value, report.md label, caption label].
const OUTCOMES = [
  ['conformant', 'conformant', 'conformant'],
  ['non-conformant', 'non-conformant', 'non-conformant'],
  ['partial', 'partial', 'partial'],
  ['not_applicable', 'not applicable', 'not applicable'],
  ['not_assessed', 'not assessed', 'not assessed'],
  ['insufficient_evidence', 'insufficient evidence', 'insufficient evidence'],
];
// The caption always names these three, even at zero, so the page never hides insufficient evidence.
const ALWAYS = new Set(['conformant', 'insufficient_evidence', 'not_assessed']);

const escapeHtml = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

/** Run the real quickstart in a scratch directory and return what the hero needs from it. */
export function runQuickstart() {
  const scratch = mkdtempSync(join(tmpdir(), 'quickstart-hero-'));
  try {
    const env = { ...process.env };
    delete env.VIRTUAL_ENV;
    const run = spawnSync(
      'uv',
      ['run', '--project', join(ROOT, 'engines', 'python'), '--frozen', 'agentce', 'quickstart', '--out', './out'],
      { cwd: scratch, env, encoding: 'utf8' },
    );
    if (run.error || run.status !== 0) {
      const why = run.error ? run.error.message : `exit ${run.status}\n${run.stderr}`;
      throw new Error(`quickstart did not run: ${why}`);
    }
    const stdout = run.stdout.replace(/\n+$/, '');
    const report = readFileSync(join(scratch, 'out', 'report.md'), 'utf8').split('\n');
    const assertions = JSON.parse(readFileSync(join(scratch, 'out', 'assertions.json'), 'utf8'));
    const counts = {};
    for (const a of assertions) counts[a.outcome] = (counts[a.outcome] ?? 0) + 1;
    const controls = new Set(assertions.map((a) => a.control)).size;
    return { stdout, report, counts, total: assertions.length, controls };
  } finally {
    rmSync(scratch, { recursive: true, force: true });
  }
}

/** The lines of report.md up to and including the last Outcome-summary bullet, checked against the tally. */
export function summaryLines(run) {
  const start = run.report.indexOf('## Outcome summary');
  if (start < 0) throw new Error('report.md has no "## Outcome summary" section');
  let end = start + 1;
  const bullet = /^- (.+): (\d+)$/;
  while (end < run.report.length && (run.report[end] === '' || bullet.test(run.report[end]))) end += 1;
  while (run.report[end - 1] === '') end -= 1;
  const shown = {};
  for (const line of run.report.slice(start, end)) {
    const m = bullet.exec(line);
    if (m) shown[m[1]] = Number(m[2]);
  }
  for (const [key, label] of OUTCOMES) {
    if ((shown[label] ?? 0) !== (run.counts[key] ?? 0)) {
      throw new Error(`report.md says ${shown[label] ?? 0} ${label}, assertions.json has ${run.counts[key] ?? 0}`);
    }
  }
  return run.report.slice(0, end);
}

/** "25 conformant, 19 insufficient evidence, 5 not assessed": the three outcomes every page names, plus any other that occurred. */
function tallyList(run) {
  const order = ['conformant', 'non-conformant', 'partial', 'not_applicable', 'insufficient_evidence', 'not_assessed'];
  return order
    .filter((key) => ALWAYS.has(key) || (run.counts[key] ?? 0) > 0)
    .map((key) => `${run.counts[key] ?? 0} ${OUTCOMES.find(([k]) => k === key)[2]}`)
    .join(', ');
}

/** "49 controls" when each control has one assertion (one subject), otherwise "49 assertions". */
const totalPhrase = (run) => `${run.total} ${run.controls === run.total ? 'controls' : 'assertions'}`;

/** The hero block: the terminal transcript of the run, then a caption stating its tally. */
export function renderRegion(run) {
  const lines = summaryLines(run);
  const head = `head -n ${lines.length} out/report.md`;
  const transcript = [
    `<span class="c-prompt">$</span> <span class="c-cmd">${escapeHtml(COMMAND)}</span>`,
    escapeHtml(run.stdout),
    '',
    `<span class="c-prompt">$</span> <span class="c-cmd">${escapeHtml(head)}</span>`,
    ...lines.map(escapeHtml),
  ].join('\n');
  return [
    `      <pre><code>${transcript}</code></pre>`,
    '      <figcaption>',
    `        The real output of that command over the bundled <code>corpus/quickstart</code> project: ${tallyList(run)}, of ${totalPhrase(run)}.`,
    '        Insufficient evidence means a control applies and was evaluated, but the evidence collected did not meet its minimum;',
    '        it is a gap in what was collected, not a failure and not a guess.',
    '      </figcaption>',
  ].join('\n');
}

/** The Markdown block: the run's tally, then what the two outcomes that are not pass or fail mean. */
export function renderTally(run) {
  return [
    `A run over this project ends with ${tallyList(run)}, of ${totalPhrase(run)}.`,
    '',
    '- **Insufficient evidence** means the control applies and was evaluated, but the evidence collected did not meet its minimum evidence or source class. It is a gap in what was collected, not a failure and not a guess: the engine reports conformant only when the evidence supports it.',
    '- **Not assessed** means the control applies but was not evaluated, for example because a manual checklist is absent or a metric is below its minimum population.',
  ].join('\n');
}

// Per surface kind: the message-key prefix, the region markers, and how the region is rendered and spliced in.
const KINDS = {
  hero: { prefix: 'hero', begin: BEGIN, end: END, before: '\n', after: '\n      ', render: renderRegion },
  tally: { prefix: 'tally', begin: MD_BEGIN, end: MD_END, before: '\n\n', after: '\n\n', render: renderTally },
};
const kindOf = (path) => (path.endsWith('.astro') ? KINDS.hero : KINDS.tally);

/** Replace the marked region of a page with `region`; null if the markers are absent or misordered. */
export function spliceRegion(page, region, kind = KINDS.hero) {
  const a = page.indexOf(kind.begin);
  const b = page.indexOf(kind.end);
  if (a < 0 || b < 0 || b < a) return null;
  return `${page.slice(0, a + kind.begin.length)}${kind.before}${region}${kind.after}${page.slice(b)}`;
}

const CONFORM = /\b(?:conformant|conforms?|pass(?:es|ed|ing)?)\b/gi;
const UNIVERSAL = /\b(?:every|all)\b|100\s?%|\bfully\b/i;
const SUBJECT = /\b(?:controls?|verdicts?)\b/i;
const ABSOLUTE = /100\s?%|\bfully\b|across the board/i;
const WINDOW = 100;

/**
 * Whether the text asserts that everything conforms: every/all/100%/fully together with control(s) or
 * verdict(s) and conformant/pass in any order and any wording, or a bare absolute ("100% conformant",
 * "fully conformant", "conformant across the board"). Anchored on each conformant/pass word and searched in
 * both directions inside its sentence, on whitespace-normalised text so a hard line wrap cannot hide a claim.
 */
export function blanketClaim(text) {
  for (const sentence of text.replace(/\s+/g, ' ').split('.')) {
    for (const m of sentence.matchAll(CONFORM)) {
      const chunk = sentence.slice(Math.max(0, m.index - WINDOW), Math.min(sentence.length, m.index + m[0].length + WINDOW));
      if ((UNIVERSAL.test(chunk) && SUBJECT.test(chunk)) || ABSOLUTE.test(chunk)) return true;
    }
  }
  return false;
}

/** Empty when the page equals what a fresh run generates; otherwise the reasons it does not. */
export function checkPage(page, run, kind = KINDS.hero) {
  const problems = [];
  for (const phrase of FORBIDDEN) {
    if (page.includes(phrase)) problems.push(`${kind.prefix}.forbidden_claim: the page states "${phrase}"`);
  }
  const allConformant = run.total > 0 && (run.counts.conformant ?? 0) === run.total;
  if (!allConformant && blanketClaim(page)) {
    problems.push(`${kind.prefix}.blanket_claim: the page claims every control is conformant; the run does not`);
  }
  const fresh = spliceRegion(page, kind.render(run), kind);
  if (fresh === null) problems.push(`${kind.prefix}.markers_missing: the quickstart-run markers are absent from the page`);
  else if (fresh !== page) problems.push(`${kind.prefix}.drift: the page differs from a fresh quickstart run`);
  return problems;
}

function selfTest() {
  const run = {
    stdout: 'quickstart complete: 5 assertions; report in ./out',
    report: [
      '# AgentCE conformance report',
      '',
      '## Outcome summary',
      '',
      '- conformant: 3',
      '- non-conformant: 0',
      '- partial: 0',
      '- not applicable: 0',
      '- not assessed: 1',
      '- insufficient evidence: 1',
      '',
      '## Assertions',
    ],
    counts: { conformant: 3, not_assessed: 1, insufficient_evidence: 1 },
    total: 5,
    controls: 5,
  };
  const changed = {
    ...run,
    counts: { ...run.counts, conformant: 2, not_assessed: 2 },
    report: run.report.map((l) => l.replace('conformant: 3', 'conformant: 2').replace('assessed: 1', 'assessed: 2')),
  };
  const heroShell = `<figure>\n      ${BEGIN}\n      ${END}\n    </figure>`;
  const mdShell = `Intro.\n\n${MD_BEGIN}\n${MD_END}\n\nOutro.\n`;
  const hero = spliceRegion(heroShell, renderRegion(run), KINDS.hero);
  const md = spliceRegion(mdShell, renderTally(run), KINDS.tally);
  const cases = [
    ['a hero generated from the run passes', hero, run, KINDS.hero, []],
    ['a changed hero tally is drift', hero.replace('3 conformant', '4 conformant'), run, KINDS.hero, ['hero.drift']],
    ['a run that changed under the hero is drift', hero, changed, KINDS.hero, ['hero.drift']],
    ['a hand-written all-pass claim is refused', hero.replace('</figure>', '<p>every control conformant</p></figure>'), run, KINDS.hero, ['hero.forbidden_claim', 'hero.blanket_claim']],
    ['a hero without markers is refused', '<figure></figure>', run, KINDS.hero, ['hero.markers_missing']],
    ['a Markdown block generated from the run passes', md, run, KINDS.tally, []],
    ['a changed Markdown tally is drift', md.replace('3 conformant', '4 conformant'), run, KINDS.tally, ['tally.drift']],
    ['a run that changed under the Markdown page is drift', md, changed, KINDS.tally, ['tally.drift']],
    ['a Markdown page without markers is refused', 'Intro.\n', run, KINDS.tally, ['tally.markers_missing']],
    ['a softened blanket claim is refused', `${md}\nAll controls are conformant across the board.\n`, run, KINDS.tally, ['tally.blanket_claim']],
    ['a claim split over a wrapped line is refused', `${md}\nEvery base-catalog control\nis conformant.\n`, run, KINDS.tally, ['tally.blanket_claim']],
    ['an honest partial tally is not a blanket claim', `${md}\n3 of 5 controls are conformant.\n`, run, KINDS.tally, []],
    [
      'a blanket claim is allowed when the run is all-conformant',
      spliceRegion(`${mdShell}\nEvery control is conformant.\n`, renderTally({ ...run, counts: { conformant: 5 } }), KINDS.tally),
      { ...run, counts: { conformant: 5 } },
      KINDS.tally,
      [],
    ],
  ];
  let failed = 0;
  for (const [name, page, r, kind, expect] of cases) {
    const got = checkPage(page, r, kind).map((p) => p.split(':')[0]);
    const ok = got.length === expect.length && expect.every((k) => got.includes(k));
    console.log(`${ok ? 'ok  ' : 'FAIL'} self-test: ${name}${ok ? '' : ` (expected [${expect}], got [${got}])`}`);
    if (!ok) failed += 1;
  }
  let inconsistent = false;
  try {
    summaryLines({ ...run, counts: { ...run.counts, conformant: 9 } });
  } catch {
    inconsistent = true;
  }
  console.log(`${inconsistent ? 'ok  ' : 'FAIL'} self-test: a report that disagrees with assertions.json is refused`);
  if (!inconsistent) failed += 1;
  return failed === 0 ? 0 : 1;
}

function main(argv) {
  if (argv.includes('--self-test')) return selfTest();
  let run;
  try {
    run = runQuickstart();
  } catch (err) {
    console.error(`hero.run_failed: ${err.message}`);
    return 2;
  }
  const given = argv.filter((a) => !a.startsWith('--'));
  const pages = given.length > 0 ? given : SURFACES;
  const write = argv.includes('--write');
  let failed = 0;
  for (const path of pages) {
    const kind = kindOf(path);
    const page = readFileSync(path, 'utf8');
    if (write) {
      const next = spliceRegion(page, kind.render(run), kind);
      if (next === null) {
        console.error(`${kind.prefix}.markers_missing: the quickstart-run markers are absent from ${path}`);
        failed += 1;
      } else {
        writeFileSync(path, next);
      }
      continue;
    }
    const problems = checkPage(page, run, kind);
    for (const p of problems) console.error(`${p} (${path})`);
    if (problems.length > 0) failed += 1;
  }
  if (failed > 0) {
    if (!write) console.error('fix: node scripts/quickstart-hero.mjs --write');
    return 1;
  }
  const noun = pages.length === 1 ? 'surface equals' : 'surfaces equal';
  console.log(
    write
      ? `quickstart-hero: wrote ${pages.length} ${pages.length === 1 ? 'surface' : 'surfaces'} from a fresh run (${run.total} assertions)`
      : `quickstart-hero: ${pages.length} ${noun} a fresh quickstart run (${run.total} assertions)`,
  );
  return 0;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  process.exit(main(process.argv.slice(2)));
}
