#!/usr/bin/env python3
"""Regenerate the Java engine's byte-identical goldens from the Python reference engine.

Run from the repository root with:

    env -u VIRTUAL_ENV uv run --project engines/python --frozen \\
        python engines/java/src/test/resources/testdata/generate_goldens.py

Add ``--check`` to compare every golden with the live Python engine and write nothing (exit 1 names
each stale, missing or unproduced golden); VG-ENGINE-GOLDENS-FRESH runs it.

Why this script exists: ``engines/java/src/test/java/org/agentce/{Assess,Catalog,Report}Test.java``
each assert that the Java engine's output is byte-identical (after RFC 8785 canonicalisation, or
exactly for the human-readable renderers) to the Python reference engine's output over the real
``spec/catalogs/base/eu-ai-act`` catalog. The goldens this script writes under
``engines/java/src/test/resources/testdata/`` are, by design, captures of the *Python reference
engine's* output -- never the Java engine's own output, because comparing the Java engine to itself
would make the parity tests vacuous. Whenever the base catalog gains, removes, or changes a control,
shape, or test fixture, these goldens go stale and must be regenerated by re-running this script
against the then-current catalog. It imports the ``agentce`` package directly (never the Java engine)
and mirrors the exact scenarios ``AssessTest``/``CatalogTest``/``ReportTest`` build in Java.

Known, tracked divergence this script preserves rather than fixes: ``Report.renderReportMd``/
``renderReportHtml`` in the Java engine do not yet render the ``## Provenance`` section (or its HTML
section) that the Python reference always appends -- bringing the Java renderer to parity there is
separate, untouched work, so the ``md``/``html`` golden fields are trimmed to the point the Provenance
section would start, matching what the Java renderer actually produces today. Widening this script's
scope to add that section is not this script's job.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[6]
sys.path.insert(0, str(REPO / "engines" / "python"))
sys.path.insert(0, str(REPO / "engines" / "python" / "tests"))

from agentce.assertions import Assertion, aggregate  # noqa: E402
from agentce.assess import assess_subjects  # noqa: E402
from agentce.catalog import Catalog, load_catalog  # noqa: E402
from agentce.domain import DomainBinding  # noqa: E402
from agentce.graph import build_graph  # noqa: E402
from agentce.profile import Profile  # noqa: E402
from agentce.report import (  # noqa: E402
    render_evidence_pack,
    render_oscal,
    render_report_html,
    render_report_md,
    render_sarif,
)
from agentce.structural import evaluate_control  # noqa: E402
from parity_goldens import shared_goldens, write_or_check  # noqa: E402

BASE = REPO / "spec" / "catalogs" / "base" / "eu-ai-act"
CONDUCT = REPO / "spec" / "catalogs" / "overlays" / "conduct"
TESTDATA = REPO / "engines" / "java" / "src" / "test" / "resources" / "testdata"
SUBJECT = "spiffe://corp/agents/a"
CASES = ("passed", "failed", "inapplicable")


def events_of(
    control_id: str, case: str, directory: Path = BASE
) -> list[dict[str, object]]:
    path = directory / "test" / control_id / f"{case}.jsonl"
    return [
        json.loads(line)
        for line in path.read_text(encoding="utf-8").split("\n")
        if line.strip()
    ]


def dump(data: object) -> str:
    """Serialise ``data`` in the same style as the existing goldens: 2-space indent, insertion order
    preserved (not sorted -- ``Canonical.canonicalString`` on the Java side sorts for comparison; the
    file's own order just mirrors this script's, as the existing goldens already do), a trailing
    newline."""
    return json.dumps(data, indent=2) + "\n"


def without_provenance_md(md: str) -> str:
    marker = "\n## Provenance\n"
    idx = md.index(marker)
    return md[:idx]


def without_provenance_html(html: str) -> str:
    marker = '<section aria-labelledby="provenance">'
    idx = html.index(marker)
    end_idx = html.index("<footer>", idx)
    return html[:idx] + html[end_idx:]


def build_assess_golden(catalog: Catalog, domain: DomainBinding) -> dict[str, object]:
    """Mirrors AssessTest.assessSubjectsMatchesReference's scenario map exactly (insertion order)."""
    profile = Profile.from_dict(
        {
            "subjects": [{"id": SUBJECT, "role": "both"}],
            "catalogs": ["base/eu-ai-act"],
        }
    )
    scenarios: dict[str, list[dict[str, object]]] = {
        "ovs-passed": events_of("OVS-03", "passed"),
        "ovs-failed": events_of("OVS-03", "failed"),
        "rec-passed": events_of("REC-04", "passed"),
        "empty": [],
    }
    result: dict[str, object] = {}
    for name, events in scenarios.items():
        assertions = assess_subjects(events, profile, [catalog], domain)
        result[name] = [a.to_json() for a in assertions]
    return result


def build_catalog_golden(
    catalog: Catalog, domain: DomainBinding, directory: Path = BASE
) -> dict[str, object]:
    """Mirrors CatalogTest.structuralEvaluationMatchesReference: skip a control with no usable shape,
    skip a case with no fixture, but still record every control that has a shape (even with an empty
    per-case map) exactly as the Java loop does. ``directory`` is the catalog's own directory (its
    fixtures live under ``directory/test/<control>/<case>.jsonl``); the conduct-overlay golden below
    reuses this same function over a different catalog and directory, never duplicating it."""
    result: dict[str, object] = {}
    for control in catalog.controls:
        shape = catalog.shape_for(control)
        if shape is None:
            continue
        per_case: dict[str, object] = {}
        for case in CASES:
            fixture = directory / "test" / control.id / f"{case}.jsonl"
            if not fixture.is_file():
                continue
            events = events_of(control.id, case, directory)
            store = build_graph(events, domain=domain)
            outcome = evaluate_control(
                store,
                shape,
                catalog.shapes,
                control_id=control.id,
                tolerance=control.tolerance,
            )
            per_case[case] = outcome.to_json()
        result[control.id] = per_case
    return result


#: Mirrors ReportTest.verdictCasesMatchReference's VERDICT_CASES (same three scenarios as the
#: TypeScript generator uses, since both tests exercise the identical synthetic fixture set).
VERDICT_CASES: list[list[list[str]]] = [
    [
        *(
            [f"DAT-{n:02d}", "spiffe://corp/agents/a", "insufficient_evidence"]
            for n in range(8, 0, -1)
        ),
        ["DOC-01", "spiffe://corp/agents/a", "conformant"],
        ["DOC-05", "spiffe://corp/agents/a", "not_assessed"],
        ["OVS-09", "spiffe://corp/agents/a", "not_assessed"],
    ],
    [
        ["DOC-01", "spiffe://corp/agents/a", "conformant"],
        ["DOC-02", "spiffe://corp/agents/a", "conformant"],
        ["INC-02", "spiffe://corp/agents/a", "not_applicable"],
    ],
    [
        ["OVS-02", "spiffe://corp/agents/a", "non-conformant"],
        ["OVS-02", "spiffe://corp/agents/b", "non-conformant"],
        ["REC-01", "spiffe://corp/agents/a", "partial"],
        ["REC-02", "spiffe://corp/agents/b", "insufficient_evidence"],
    ],
]


def build_verdict_cases() -> list[dict[str, object]]:
    cases: list[dict[str, object]] = []
    for rows in VERDICT_CASES:
        assertions = [
            Assertion(
                control=control,
                control_version="2026.09",
                subject=subject,
                outcome=outcome,
                rung=2,
                mode="automated",
                window=("2026-01-01T00:00:00Z", "2026-04-01T00:00:00Z"),
                population=(1, 1 if outcome == "non-conformant" else 0),
                severity="high",
                family=control.split("-", 1)[0] if "-" in control else control,
            )
            for control, subject, outcome in rows
        ]
        counts = aggregate(assertions)
        cases.append(
            {
                "assertions": rows,
                "md": without_provenance_md(render_report_md(assertions, counts)),
                "html": without_provenance_html(render_report_html(assertions, counts)),
            }
        )
    return cases


def build_report_golden(catalog: Catalog, domain: DomainBinding) -> dict[str, object]:
    """Mirrors ReportTest's ovsFailedAssertions() and both its test methods."""
    profile = Profile.from_dict({"subjects": [{"id": SUBJECT, "role": "both"}]})
    events = events_of("OVS-03", "failed")
    assertions: list[Assertion] = assess_subjects(events, profile, [catalog], domain)
    counts = aggregate(assertions)

    return {
        "md": without_provenance_md(render_report_md(assertions, counts)),
        "html": without_provenance_html(render_report_html(assertions, counts)),
        "oscal": render_oscal(assertions),
        "sarif": render_sarif(assertions),
        "pack": render_evidence_pack(SUBJECT, assertions),
        "assertions": [a.to_json() for a in assertions],
        "verdict_cases": build_verdict_cases(),
    }


def goldens() -> dict[str, str]:
    """Every golden this engine's parity tests read, file name -> the exact text to commit."""
    catalog = load_catalog(BASE)
    domain = DomainBinding.load(BASE / "test" / "domain.yaml")
    # The Conduct overlay (SPEC §7.7) is a separate catalog with its own fixtures; a real,
    # user-reachable guard that CND-01/CND-05 (withinScope/actsOnUntrusted) are materialised the
    # same way Python does -- found missing from TS/Java entirely in 18.37, ported, and guarded here
    # so a future regression in either engine's graph builder turns this golden red.
    conduct_catalog = load_catalog(CONDUCT)
    conduct_domain = DomainBinding.load(CONDUCT / "test" / "domain.yaml")
    return {
        "assess-golden.json": dump(build_assess_golden(catalog, domain)),
        "catalog-golden.json": dump(build_catalog_golden(catalog, domain)),
        "report-golden.json": dump(build_report_golden(catalog, domain)),
        "conduct-golden.json": dump(
            build_catalog_golden(conduct_catalog, conduct_domain, CONDUCT)
        ),
        **shared_goldens(TESTDATA, dump),
    }


if __name__ == "__main__":
    sys.exit(write_or_check(TESTDATA, goldens(), sys.argv[1:]))
