#!/usr/bin/env python3
"""Regenerate the Java engine's byte-identical goldens from the Python reference engine.

Run with:

    cd /Users/willsct/agentce && env -u VIRTUAL_ENV uv run --project engines/python --frozen \\
        python engines/java/src/test/resources/testdata/generate_goldens.py

Why this script exists: ``engines/java/src/test/java/org/agentce/{Assess,Report}Test.java`` each
assert that the Java engine's output is byte-identical (after RFC 8785 canonicalisation, or exactly
for the human-readable renderers) to the Python reference engine's output over the real
``spec/catalogs/base/eu-ai-act`` catalog. The goldens this script writes under
``engines/java/src/test/resources/testdata/`` are, by design, captures of the *Python reference
engine's* output -- never the Java engine's own output, because comparing the Java engine to itself
would make the parity tests vacuous. Whenever the base catalog gains, removes, or changes a control,
shape, or test fixture, these goldens go stale and must be regenerated by re-running this script
against the then-current catalog. It imports the ``agentce`` package directly (never the Java engine)
and mirrors the exact scenarios ``AssessTest``/``ReportTest`` build in Java.

Known, tracked divergence this script preserves rather than fixes: ``Report.renderReportMd``/
``renderReportHtml`` in the Java engine do not yet render the ``## Provenance`` section (or its HTML
section) that the Python reference always appends -- bringing the Java renderer to parity there is
separate, untouched work, so the ``md``/``html`` golden fields are trimmed to the point the Provenance
section would start, matching what the Java renderer actually produces today. Widening this script's
scope to add that section is not this script's job.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[6]
sys.path.insert(0, str(REPO / "engines" / "python"))

from agentce.assertions import Assertion, aggregate  # noqa: E402
from agentce.assess import assess_subjects  # noqa: E402
from agentce.catalog import Catalog, load_catalog  # noqa: E402
from agentce.domain import DomainBinding  # noqa: E402
from agentce.profile import Profile  # noqa: E402
from agentce.report import (  # noqa: E402
    render_evidence_pack,
    render_oscal,
    render_report_html,
    render_report_md,
    render_sarif,
)

BASE = REPO / "spec" / "catalogs" / "base" / "eu-ai-act"
TESTDATA = REPO / "engines" / "java" / "src" / "test" / "resources" / "testdata"
SUBJECT = "spiffe://corp/agents/a"


def events_of(control_id: str, case: str) -> list[dict[str, object]]:
    path = BASE / "test" / control_id / f"{case}.jsonl"
    return [
        json.loads(line)
        for line in path.read_text(encoding="utf-8").split("\n")
        if line.strip()
    ]


def write_golden(name: str, data: object) -> None:
    """Write ``data`` in the same style as the existing goldens: 2-space indent, insertion order
    preserved (not sorted -- ``Canonical.canonicalString`` on the Java side sorts for comparison; the
    file's own order just mirrors this script's, as the existing goldens already do), a trailing
    newline, and no other file touched."""
    path = TESTDATA / name
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {path}")


def without_provenance_md(md: str) -> str:
    marker = "\n## Provenance\n"
    idx = md.index(marker)
    return md[:idx]


def without_provenance_html(html: str) -> str:
    marker = '<section aria-labelledby="provenance">'
    idx = html.index(marker)
    end_idx = html.index("<footer>", idx)
    return html[:idx] + html[end_idx:]


def build_assess_golden(catalog: Catalog, domain: DomainBinding) -> dict[str, object]:
    """Mirrors AssessTest.assessSubjectsMatchesReference's scenario map exactly (insertion order)."""
    profile = Profile.from_dict(
        {
            "subjects": [{"id": SUBJECT, "role": "both"}],
            "catalogs": ["base/eu-ai-act"],
        }
    )
    scenarios: dict[str, list[dict[str, object]]] = {
        "ovs-passed": events_of("OVS-03", "passed"),
        "ovs-failed": events_of("OVS-03", "failed"),
        "rec-passed": events_of("REC-04", "passed"),
        "empty": [],
    }
    result: dict[str, object] = {}
    for name, events in scenarios.items():
        assertions = assess_subjects(events, profile, [catalog], domain)
        result[name] = [a.to_json() for a in assertions]
    return result


#: Mirrors ReportTest.verdictCasesMatchReference's VERDICT_CASES (same three scenarios as the
#: TypeScript generator uses, since both tests exercise the identical synthetic fixture set).
VERDICT_CASES: list[list[list[str]]] = [
    [
        *(
            [f"DAT-{n:02d}", "spiffe://corp/agents/a", "insufficient_evidence"]
            for n in range(8, 0, -1)
        ),
        ["DOC-01", "spiffe://corp/agents/a", "conformant"],
        ["DOC-05", "spiffe://corp/agents/a", "not_assessed"],
        ["OVS-09", "spiffe://corp/agents/a", "not_assessed"],
    ],
    [
        ["DOC-01", "spiffe://corp/agents/a", "conformant"],
        ["DOC-02", "spiffe://corp/agents/a", "conformant"],
        ["INC-02", "spiffe://corp/agents/a", "not_applicable"],
    ],
    [
        ["OVS-02", "spiffe://corp/agents/a", "non-conformant"],
        ["OVS-02", "spiffe://corp/agents/b", "non-conformant"],
        ["REC-01", "spiffe://corp/agents/a", "partial"],
        ["REC-02", "spiffe://corp/agents/b", "insufficient_evidence"],
    ],
]


def build_verdict_cases() -> list[dict[str, object]]:
    cases: list[dict[str, object]] = []
    for rows in VERDICT_CASES:
        assertions = [
            Assertion(
                control=control,
                control_version="2026.09",
                subject=subject,
                outcome=outcome,
                rung=2,
                mode="automated",
                window=("2026-01-01T00:00:00Z", "2026-04-01T00:00:00Z"),
                population=(1, 1 if outcome == "non-conformant" else 0),
                severity="high",
                family=control.split("-", 1)[0] if "-" in control else control,
            )
            for control, subject, outcome in rows
        ]
        counts = aggregate(assertions)
        cases.append(
            {
                "assertions": rows,
                "md": without_provenance_md(render_report_md(assertions, counts)),
                "html": without_provenance_html(render_report_html(assertions, counts)),
            }
        )
    return cases


def build_report_golden(catalog: Catalog, domain: DomainBinding) -> dict[str, object]:
    """Mirrors ReportTest's ovsFailedAssertions() and both its test methods."""
    profile = Profile.from_dict({"subjects": [{"id": SUBJECT, "role": "both"}]})
    events = events_of("OVS-03", "failed")
    assertions: list[Assertion] = assess_subjects(events, profile, [catalog], domain)
    counts = aggregate(assertions)

    return {
        "md": without_provenance_md(render_report_md(assertions, counts)),
        "html": without_provenance_html(render_report_html(assertions, counts)),
        "oscal": render_oscal(assertions),
        "sarif": render_sarif(assertions),
        "pack": render_evidence_pack(SUBJECT, assertions),
        "assertions": [a.to_json() for a in assertions],
        "verdict_cases": build_verdict_cases(),
    }


def main() -> None:
    catalog = load_catalog(BASE)
    domain = DomainBinding.load(BASE / "test" / "domain.yaml")

    write_golden("assess-golden.json", build_assess_golden(catalog, domain))
    write_golden("report-golden.json", build_report_golden(catalog, domain))


if __name__ == "__main__":
    main()
