"""Repository check: the message-key catalogue is complete (SPEC §13.4 AX-6).

Parses the committed ``docs/errors.md`` (generated by ``agentce doctor --write-errors``) and fails if
any message key lacks a cause or a fix, or if a required key — every quarantine reason (SPEC
Appendix F) and the ``insufficient_evidence`` explanation — is missing. Stdlib only, so this repo
check carries no dependencies; the engine's own tests guard that ``docs/errors.md`` is current.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

_ERRORS_MD = Path(__file__).resolve().parent.parent / "docs" / "errors.md"

#: The keys that must always be documented (SPEC Appendix F quarantine reasons + the evidence gap).
_REQUIRED_KEYS = frozenset(
    {
        "schema_invalid",
        "duplicate_id",
        "time_order",
        "unknown_type",
        "unknown_source",
        "class_mismatch",
        "oversize",
        "context_mismatch",
        "insufficient_evidence",
    }
)

_ROW = re.compile(r"^\|\s*`([^`]+)`\s*\|\s*(.*?)\s*\|\s*(.*?)\s*\|\s*$")


def check(text: str) -> list[str]:
    problems: list[str] = []
    keys: set[str] = set()
    for line in text.splitlines():
        match = _ROW.match(line)
        if not match:
            continue
        key, cause, fix = match.group(1), match.group(2), match.group(3)
        keys.add(key)
        if not cause:
            problems.append(f"{key}: no cause")
        if not fix:
            problems.append(f"{key}: no fix")
    for required in sorted(_REQUIRED_KEYS - keys):
        problems.append(f"{required}: missing from the catalogue")
    return problems


def main() -> int:
    if not _ERRORS_MD.is_file():
        print(f"{_ERRORS_MD} is missing; run `agentce doctor --write-errors docs/errors.md`", file=sys.stderr)
        return 2
    problems = check(_ERRORS_MD.read_text(encoding="utf-8"))
    if problems:
        for problem in problems:
            print(problem, file=sys.stderr)
        print(f"ERRORS CATALOGUE INCOMPLETE: {len(problems)} problem(s)", file=sys.stderr)
        return 1
    print("ERRORS OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
