// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import focusablePre from './src/plugins/a11y-focusable-pre.mjs';

// The canonical origin. Every dereferenceable IRI the specification defines resolves under this host,
// so the site is built with it fixed here (used for canonical links, Open Graph, and the sitemap).
export default defineConfig({
  site: 'https://agent-conformance.org',
  integrations: [
    // Keyboard access for scrollable code blocks (WCAG 2.1.1); enforced by the axe gate in scripts/check-a11y.mjs.
    focusablePre(),
    starlight({
      title: 'Agent Conformance',
      description:
        'A deterministic, model-free, vendor-neutral standard for assessing how AI agents behave — with reproducible evidence.',
      customCss: ['./src/styles/tokens.css'],
      // English is the single normative language (SPEC) and the only complete content today; the other
      // eight are declared so Starlight's own i18n routing exists (per-locale pages, lang/hreflang
      // metadata, a localized sitemap) and falls back to English content page-by-page until a community
      // translation lands with reviewer sign-off. No machine translation ships as part of declaring them.
      defaultLocale: 'root',
      locales: {
        root: { label: 'English', lang: 'en' },
        es: { label: 'Español', lang: 'es' },
        fr: { label: 'Français', lang: 'fr' },
        ja: { label: '日本語', lang: 'ja' },
        'zh-hans': { label: '简体中文', lang: 'zh-Hans' },
        pl: { label: 'Polski', lang: 'pl' },
        'pt-br': { label: 'Português do Brasil', lang: 'pt-BR' },
        uk: { label: 'Українська', lang: 'uk' },
        ru: { label: 'Русский', lang: 'ru' },
      },
      social: [
        {
          icon: 'github',
          label: 'GitHub',
          href: 'https://github.com/agent-conformance/agentce',
        },
      ],
      // Documentation lives under /docs (content authored in src/content/docs/docs/**); the landing
      // page at / is a custom Astro page (src/pages/index.astro) outside the Starlight route tree.
      sidebar: [
        {
          label: 'Documentation',
          items: [
            { label: 'Install', slug: 'docs/install' },
            { label: 'Getting Started', slug: 'docs/getting-started' },
            { label: 'What is agent conformance?', slug: 'docs/concepts' },
            { label: 'The Conformance Spec', slug: 'docs/specification' },
            { label: 'Running Assessments', slug: 'docs/running-assessments' },
            { label: 'Authoring a Catalog', slug: 'docs/catalog-authoring' },
            { label: 'Runtime and Continuous Conformance', slug: 'docs/runtime-conformance' },
            { label: 'Trace-Store Connectors', slug: 'docs/trace-store-connectors' },
            { label: 'CI Integration', slug: 'docs/ci-integration' },
            { label: 'Contributing', slug: 'docs/contributing' },
          ],
        },
        {
          label: 'Accessibility',
          items: [
            { label: 'Accessibility Statement', slug: 'docs/accessibility-statement' },
            { label: 'VPAT / Conformance Report', slug: 'docs/vpat' },
            { label: 'Accessibility Test Protocol', slug: 'docs/accessibility-testing-protocol' },
          ],
        },
        // Generated from the sources by docs/build.py --publish (SPEC §13.4): a CLI, adapter,
        // control-family, evidence-model, and report-schema page per real command/control/class/schema.
        // Autogenerated so a new page never needs a sidebar edit to reach a reader.
        { label: 'Reference', items: [{ autogenerate: { directory: 'reference' } }] },
        // Understanding-oriented pages published from docs/ (the threat model, the verification
        // procedure, the message-key catalogue).
        { label: 'Explanation', items: [{ autogenerate: { directory: 'explanation' } }] },
      ],
    }),
  ],
});
